# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontrola',
            old_name='name',
            new_name='Nazwa',
        ),
        migrations.AddField(
            model_name='kontrola',
            name='Model',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
