# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrola', '0003_auto_20171201_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kontrola',
            new_name='KontrolaHardware',
        ),
    ]
