# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrola', '0005_kontrolahardware_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrolahardware',
            name='update',
            field=models.DateTimeField(),
        ),
    ]
