# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrola', '0010_auto_20171201_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontrolahardware',
            old_name='Last_Update',
            new_name='timestemp',
        ),
    ]
