# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrola', '0011_auto_20171201_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontrolahardware',
            old_name='Podzespół',
            new_name='podzespół',
        ),
        migrations.RenameField(
            model_name='kontrolahardware',
            old_name='Model',
            new_name='producent',
        ),
        migrations.RenameField(
            model_name='kontrolahardware',
            old_name='Update',
            new_name='update',
        ),
    ]
