# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kontrola', '0012_auto_20171201_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontrolahardware',
            old_name='timestemp',
            new_name='timestamp',
        ),

    ]
