# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrola', '0013_auto_20171204_0830'),
    ]

    operations = [

    ]
