# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrola', '0014_auto_20171204_0839'),
    ]

    operations = [

    ]
