# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 08:56
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify

import string
import random

def id_generator():
    size=16
    chars=string.ascii_lowercase + string.digits
    return ''.join(random.choice(chars) for x in range(size))




class Migration(migrations.Migration):

    dependencies = [
        ('kontrola', '0015_remove_kontrolahardware_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrolahardware',
            name='slug',
            field=models.TextField(blank=True, null=True, max_length=100),
        ),

    ]
