# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrola', '0018_auto_20171204_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontrolahardware',
            name='podzespół',
        ),
    ]
