# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrola', '0019_remove_kontrolahardware_podzespół'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrolahardware',
            name='podzespol',
            field=models.CharField(default='dupa', max_length=120),
            preserve_default=False,
        ),
    ]
